SELECT 'Upgrading MetaStore schema from 3.3.0 to 3.1.3' AS Status from dual;

-- HIVE-20221: change PARTITION_PARAMS.PARAM_VALUE to CLOB
ALTER TABLE PARTITION_PARAMS ADD (TEMP CLOB);
UPDATE PARTITION_PARAMS SET TEMP=PARAM_VALUE, PARAM_VALUE=NULL;
ALTER TABLE PARTITION_PARAMS DROP COLUMN PARAM_VALUE;
ALTER TABLE PARTITION_PARAMS RENAME COLUMN TEMP TO PARAM_VALUE;

UPDATE VERSION SET SCHEMA_VERSION='3.1.3', VERSION_COMMENT='Hive release version 3.1.3' where VER_ID=1;
SELECT 'Finished upgrading MetaStore schema from 3.1.0 to 3.1.3' AS Status from dual;

