SELECT 'Upgrading MetaStore schema from 3.1.0 to 3.1.3' AS MESSAGE;

-- HIVE-20221: change PARTITION_PARAMS.PARAM_VALUE to nvarchar(MAX)
ALTER TABLE "PARTITION_PARAMS" ALTER COLUMN "PARAM_VALUE" nvarchar(MAX);

UPDATE VERSION SET SCHEMA_VERSION='3.1.3', VERSION_COMMENT='Hive release version 3.1.3' where VER_ID=1;