SELECT 'Upgrading MetaStore schema from 3.1.0 to 3.1.3' AS ' ';

-- HIVE-20221: change PARTITION_PARAMS.PARAM_VALUE to MEDIUMTEXT
ALTER TABLE PARTITION_PARAMS MODIFY PARAM_VALUE MEDIUMTEXT;

UPDATE VERSION SET SCHEMA_VERSION='3.1.3', VERSION_COMMENT='Hive release version 3.1.3' where VER_ID=1;
SELECT 'Finished upgrading MetaStore schema from 3.1.0 to 3.1.3' AS ' ';